#!/bin/bash
#attempt at bash
declare -a array
while IFS= read -r line; do
  for (( i=0; i<${#line}; i++)); do
    c=${line:$i:1}
    if [ $c = "1" ]
    then
      $array[$i]=${array[$i]}++
    else 
      $array[$i]=${array[$i]}--
    fi
  done
done < $1

echo "${array[*]}"
